version: '2'

services:
  jekyll:
    user: "${UID}:${GID}"
    build: .
    command: sh -c "chown $UID / &&   bundle exec jekyll serve --incremental --host=0.0.0.0 "
    ports:
      - '4000:4000'
    volumes:
      - .:/srv/jekyll
