###################################################################################################
###                       THIS IS A REUSABLE WORKFLOW TO BUILD SCALA MSI                        ###
### HOW TO USE:                                                                                 ###
###   - THE RELEASE WORKFLOW SHOULD CALL THIS WORKFLOW                                          ###
###   - IT WILL UPLOAD TO GITHUB THE MSI FILE FOR SCALA UNDER THE 'scala.msi' NAME              ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - WE SHOULD BUILD SCALA USING JAVA 8                                                      ###
###################################################################################################

name: Build the MSI Package

on:
  workflow_call:

env:
  # NECESSARY FLAG TO CORRECTLY CONFIGURE THE VERSION FOR SCALA
  RELEASEBUILD: yes

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'sbt'
      - name: Build MSI package
        run: sbt 'dist-win-x86_64/Windows/packageBin'
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scala.msi
          path: ./dist/win-x86_64/target/windows/scala.msi
