name: Scala CLA
on:
  pull_request:
  push:
    branches:
      - 'language-reference-backport'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./project/scripts/check-cla.sh
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
        PUSH_AUTHOR: ${{ github.event.push.sender.login }}
