###################################################################################################
###                   THIS IS A REUSABLE WORKFLOW TO PUBLISH SCALA TO SDKMAN!                   ###
### HOW TO USE:                                                                                 ###
###   - THE RELEASE WORKFLOW SHOULD CALL THIS WORKFLOW                                          ###
###   - IT WILL PUBLISH TO SDKMAN! THE BINARIES TO EACH SUPPORTED PLATFORM AND A UNIVERSAL JAR  ###
###   - IT CHANGES THE DEFAULT VERSION IN SDKMAN!                                               ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - WE SHOULD KEEP IN SYNC THE NAME OF THE ARCHIVES WITH THE ACTUAL BUILD                   ###
###   - WE SHOULD KEEP IN SYNC THE URL OF THE RELEASE                                           ###
###################################################################################################


name: Publish Scala to SDKMAN!
run-name: Publish Scala ${{ inputs.version }} to SDKMAN!

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      CONSUMER-KEY:
        required: true
      CONSUMER-TOKEN:
        required: true 

env:
  RELEASE-URL: 'https://github.com/scala/scala3/releases/download/${{ inputs.version }}'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: LINUX_64
            archive : 'scala3-${{ inputs.version }}-x86_64-pc-linux.zip'
          - platform: LINUX_ARM64
            archive : 'scala3-${{ inputs.version }}-aarch64-pc-linux.zip'
          - platform: MAC_OSX
            archive : 'scala3-${{ inputs.version }}-x86_64-apple-darwin.zip'
          - platform: MAC_ARM64
            archive : 'scala3-${{ inputs.version }}-aarch64-apple-darwin.zip'
          - platform: WINDOWS_64
            archive : 'scala3-${{ inputs.version }}-x86_64-pc-win32.zip'
    steps:
      - uses: hamzaremmal/sdkman-release-action@978b8cdb5f9c3b83ebdc45e0a1bf97bf17cc6280
        with:
          CONSUMER-KEY   : ${{ secrets.CONSUMER-KEY }}
          CONSUMER-TOKEN : ${{ secrets.CONSUMER-TOKEN }}
          CANDIDATE      : scala
          VERSION        : ${{ inputs.version }}
          URL            : '${{ env.RELEASE-URL }}/${{ matrix.archive }}'
          PLATFORM       : ${{ matrix.platform }}
  
  default:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: hamzaremmal/sdkman-default-action@866bc79fc5bd397eeb48f9cedda2f15221c8515d
        with:
          CONSUMER-KEY   : ${{ secrets.CONSUMER-KEY }}
          CONSUMER-TOKEN : ${{ secrets.CONSUMER-TOKEN }}
          CANDIDATE      : scala
          VERSION        : ${{ inputs.version }}
