name: CI for Scala3doc

on:
  push:
    branches:
      - master
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Checkout to PR code
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run : |
          if [[ -z "${PR_NUMBER}" ]]; then
            echo Not a pull request do not need to checkout
          else
            REF=refs/pull/$PR_NUMBER/merge
            echo checking $REF
            git fetch origin $REF:$REF
            git checkout $REF
          fi     

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile and test
        run: ./project/scripts/sbt scala3doc/test

      - name: Locally publish self
        run: ./project/scripts/sbt scala3doc/publishLocal

      - name: Generate self documentation
        run: ./project/scripts/sbt scala3doc/generateSelfDocumentation

      - name: Generate testcases documentation
        run: ./project/scripts/sbt scala3doc/generateTestcasesDocumentation
        
      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          check-latest: true

      - name: Run e2e tests
        run: |
          npm --prefix ./scala3doc/e2e ci
          npm --prefix ./scala3doc/e2e run ci

      - name: Generate Scala 3 documentation
        run: ./project/scripts/sbt scala3doc/generateScala3Documentation

      - name: Generate Scala 3 stdlib documentation
        run: ./project/scripts/sbt scala3doc/generateScala3StdlibDocumentation

      - name: Generate documentation for example project using dotty-sbt
        run: ./project/scripts/sbt "sbt-dotty/scripted sbt-dotty/scala3doc"

      - name: Generate index file
        run: scala3doc/scripts/mk-index.sh scala3doc/output > scala3doc/output/index.html

      - name: Upload documentation to server
        uses: azure/CLI@v1
        env: 
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          inlineScript: |
            DOC_DEST=pr-${PR_NUMBER:-master}
            echo uplading docs to https://scala3doc.virtuslab.com/$DOC_DEST
            az storage container create --name $DOC_DEST --account-name scala3docstorage --public-access container
            az storage blob sync -s scala3doc/output -c $DOC_DEST --account-name scala3docstorage
