name: Specification

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - 'gh-readonly-queue/**'
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  DOTTY_CI_RUN: true

jobs:
  specification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/_spec

    steps:
      - uses: actions/checkout@v4

      # Keep in sync with ./docs/_spec/Dockerfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install required gems
        run: |
          gem install "rubygems-update:<3.5" --no-document
          update_rubygems
          gem install sass-embedded -v 1.58.0
          gem install bundler:1.17.2 jekyll
          bundle install
          npm install bower

      - name: Build the specification
        run: |
          bundle exec jekyll build

      # Deploy
      - name: Deployment
        env:
          USER_FOR_TEST: ${{ secrets.SPEC_DEPLOY_USER }}
        if: ${{ env.USER_FOR_TEST != '' }}
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -rzv
          path: docs/_spec/_site/
          remote_path: ${{ secrets.SPEC_DEPLOY_PATH }}
          remote_host: ${{ secrets.SPEC_DEPLOY_HOST }}
          remote_user: ${{ secrets.SPEC_DEPLOY_USER }}
          remote_key: ${{ secrets.SPEC_DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.SPEC_DEPLOY_PASS }}
